Задания всех PR-ов, объединяйтесь: архитектура + 1 + 2 + 3 + 4
GlebSolovev/RGB-rogue-like-game pull request #6
Opened 2022-05-28 12:36 UTC by GlebSolovev

2022-06-10 23:47 UTC, uncerso requested changes
![image](https://user-images.githubusercontent.com/25592720/173138886-a2b71a33-2d53-4e81-a43e-132b6b362a1e.png)
![image](https://user-images.githubusercontent.com/25592720/173138922-7ac3649c-210a-4a0a-bb21-bca5e337a54c.png)
![image](https://user-images.githubusercontent.com/25592720/173142178-cd08463c-0f7f-49a0-9862-fe8e2b5cdb10.png)

------------

Ещё у вас самореплицирующиеся мобы умеют в стены просачиваться. 
![image](https://user-images.githubusercontent.com/25592720/173142337-88cd99af-6e9d-476a-ae05-3bb521207b1e.png)

Омномном
![image](https://user-images.githubusercontent.com/25592720/173157965-a156d5fd-4670-434f-81e8-620174c3991a.png)
![image](https://user-images.githubusercontent.com/25592720/173158002-b27bb8b3-0e17-46ae-b892-3c54256f5ade.png)

В таком варианте, кстати, оно уже начинает хорошо так лагать местами. 

---------

Нужно, чтобы уровни ещё умели генерироваться. Я видел MazeGenerator, но как увидеть плоды его работы в действии?

-------------

Комментариев бы докинуть. Хоть в требованиях было ВСЕ публичные методы\поля\классы задокументировать, но, видимо, тут это без шансов. Возьмите штук 5-10 файлов, в которых можно хорошо показать свой скилл оставления комментариев, и вот всё публичное качественно покройте комментами.

---------

В четверг было прикольно, когда я читал PR, в который вы прямо докидывали комменты. Вспомнилась одна небезызвестная сказка в вариации для программистов, в которой три поросёнка чинили домик быстрее, чем волк успевал его ломать. :)

--------------

Со стратегиями и состояниями получилась каша. Плохо, конечно, что вы в чистом виде их не потрогали, но, видимо, сейчас их будет добавлять довольно бессмысленно. 

---------------

В архитектурной документации некоторые моменты пропустили.
1. У вас же есть файл `07-design-document-text.pdf`. И там есть глава `3.2. IEEE 1016-2009, структура документа`. Вот вы почему-то решили назвать разделы иначе, а заодно потерять контекст и бизнес-ограничения.
2. Нет описание типичного пользователя.
3. Диаграмма последовательностей также отсутствует.

--------------

Вы нафигачили раз в 5 больше того, что планировалось. И как бы весьма недурно нафигачили, вот только в жизни идеально никогда не сделаешь, и надо в какой-то момент остановиться. А ещё качество далеко не всегда важнее скорости (передаём привет бизнесу, где выпустить релиз на день позже конкурентов может привести к потери почти всего рынка). Я вот знаю команду с работы, у которой релиз происходит 2 раза в день (это, конечно, небольшие релизы, но без них никак). Поэтому вам стоит поучиться искать границу, когда качеством уже можно жертвовать в угоду разумных сроков (и, главное, научиться с этим мирится и жить).

---------

Итого: чтобы зачесть эти домахи надо из всех оставленных мной комментов поправить:
1) комментарии в коде
2) генерацию карты
3) архитектурное описание (я даже согласен, чтобы вы не дописывали ваши TODO, ибо по уже написанной части видно, что и так всё будет написано хорошо и это лишь вопрос времени).

2022-06-10 23:47 UTC, uncerso commented on README.md
> +./gradlew run
Прикольно. Этой командой у меня чёрное окно появляется. Ну хоть альтернативный вариант работает. Интересно, как так вышло.

Альтернативный вариант, кстати, работает через раз. Очень часто тоже просто чёрное окно.

2022-06-10 23:47 UTC, uncerso commented on README.md
> +./gradlew test
Покрытие -- это, конечно, классно, но когда запускаешь тесты, ожидаешь как минимум их увидеть: сколько тестов запустилось, сколько прошло, сколько и какие упали.

2022-06-10 23:47 UTC, uncerso commented on README.md
> +## Использование приложения
А можно управление увидеть?

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gameloaders/HeroLoader.kt
> +        50L
Лучше пишите названия полей, особенно когда они сами не могут о себе рассказать. Например, `random.nextInt(1, 4)` и `50L` вообще непонятно в этом месте, что это, и надо как минимум идти смотреть объявления HeroInitParams и InventoryDescription. И `50L`, например, так-то хорошо бы сделать константой с хорошем именем, но если будет написано при вызове конструктора HeroInitParams `singleDirMovePeriodLimit = 50L`, то тоже будет неплохо. 

-------

`singleDirMovePeriodLimit` -- вообще непонятно, в чём измеряется. Из 50L тоже размерность не следует. Надо как минимум единицу измерения добавить в название, а в идеале завести тип этой единицы измерения и принимать его.

-------

Не бойтесь упрощать код. Одна лишь строка `InventoryDescription(random.nextInt(1, 4), random.nextInt(1, 4))` содержит кучу составных частей. Поэтому, например, можно вынести `random.nextInt(1, 4)` в отдельную функцию\метод, заодно нормальным названием описав, что это такое.

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gameloaders/generators/MazeGenerator.kt
> +private data class Chamber(val lb: Cell, val ru: Cell) {
Мм, почти однобуквенные названия. Дайте угадаю: left-bottom и right-top? Ох, подождите, там `ru`, а не `rt`. Сдаюсь.

------------

В местах, где хочется принять две координаты, при этом одна должна быть больше другой, логично передавать меньшую точку и беззнаковый сдвиг (аля высота\ширина), тем самым на уровне типов запретите некорректные значения. Вы, кстати, много используете именно знаковые числа, когда они не особо нужны (например, для высоты\ширины). Может, вам будет интересно посмотреть на другой подход: 
[https://graphitemaster.github.io/aau/](https://graphitemaster.github.io/aau/)

------------

А ещё не всегда уместно добавлять в название что-то связанное с направлениями (например, left-top-bottom-right), так как если, например, вдруг в системе координат верх и низ поменяются местами, в ваших алгоритмах не поменяется вообще ничего, но названия станут уже некорректными.

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gameloaders/generators/MazeGenerator.kt
> +            c.lb.x..c.ru.x
Выглядит мемно.

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gameloaders/generators/MazeGenerator.kt
> +        for (x in xHole) grid[x, yWall] = false
В одну строку писать много всего -- к ухудшению читабельности. И с этим согласны внезапно почти все, ибо тот ещё квест найти стайлгайд, который поощряет такое написание.

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/utils/CommonUtils.kt
> +val unreachable: Nothing get() = throw IllegalStateException("reached unreachable")
В подавляющем большинстве случаев логичнее в unreachable не кидать исключение, а звать assert. 

Исключения -- для плохих, редких, но возможных ситуаций. Отвалилось соединение с сервером? Жаль, но не смертельно, ведь можно переподключиться. Закончилась память? Ок, почистим кэши и попробуем снова. 

Assert -- это утверждение о вашей программе в данной точке кода. Оно не может быть нарушено никогда. Если вдруг это произошло, то вы (программист) облажались, и теперь ваша программа творит что-то бесконтрольное. И лучше бы она перестала это делать, пока чего-нибудь плохого не натворила. Заодно можно подготовить репорт с места безумия для отправки его разработчикам (в автоматическом режиме или попросить пользователя).

Конечно, бывают случаи, когда приложение должно жить несмотря ни на что, но это редкость.

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gameloaders/factories/GenerationTable.kt
> +    fun roll(): T { // NOTE: https://youtu.be/dQw4w9WgXcQ
Чёрт, купился.

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gamelogic/entities/scriptentities/IciclesBomb.kt
> +                    }
Лучше не доводить аж до 8ого уровня вложенности.

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/utils/structures/Paths2D.kt
> +            )
Помимо формулок лучше ещё написать, что вообще за стратегия, что (как) она должна делать. Ну и что за обозначениями подразумевается.

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gamelogic/engines/behaviour/scriptbehaviours/buildingblocks/ConfuseOnCollision.kt
> +        if (message is CollidedWith && message.otherUnit.parent.fightEntity.teamId != entity.fightEntity.teamId) {
Ага-а, разговариваете с незнакомцами! 

p.s. см. закон Деметры.

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gamelogic/engines/behaviour/scriptbehaviours/meta/BurningBehaviour.kt
> +                        else (initialDurationMillis * SPREAD_BURNING_DURATION_COEFFICIENT).toLong()
Выглядит так, что можно заменить на 
`initialDurationMillis?.let { (it * SPREAD_BURNING_DURATION_COEFFICIENT).toLong() }`

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gamelogic/engines/behaviour/Lifecycle.kt
> +    suspend fun handleMessage(message: Message) {
Очень большой метод с кучей разнородной логики.

Как минимум ветки у `when (lifeCycleState) {` разнести надо в отдельные методы. Даже `when (message) {` в `LifecycleState.ONGOING` заслуживает отдельного разбиения (особенно ветка `RemoveBehaviourMessage`).

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gamelogic/engines/behaviour/Lifecycle.kt
> +                        }
Вот в отдельном методе можно вместо `else` блока, после которого ничего нет, сделать `return` и немного уменьшить уровень вложенности. Особенно актуально, когда таких ранних выходов можно сделать несколько.
```
val child = childBehaviour
if (child === message.target) {
    childBehaviour = child.childBehaviour
    child.stop()
    return
}

childBehaviour.traverseSubtree {
    val itChild = (it as? MetaBehaviour)?.childBehaviour
    if (itChild === message.target) {
        it.childBehaviour = itChild.childBehaviour
        itChild.stop()
    }
}
```

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gamelogic/engines/experience/ExperienceEngine.kt
> +        experienceLevels[Hero::class] = listOf(ExperienceLevelDescription(0, listOf(NoAction()))) + heroExperienceLevels
Большая строка, в которой куча сущностей. Можно было бы разбить на парочку:
```
val levelDescription = ExperienceLevelDescription(0, listOf(NoAction()))
experienceLevels[Hero::class] = listOf(levelDescription) + heroExperienceLevels
```

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gamelogic/engines/experience/ExperienceEngine.kt
> +        }
Вот это можно было бы вынести в отдельную check-функцию, чтобы init разными вещами не занимался и было проще читать.

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gamelogic/engines/experience/ExperienceEngine.kt
> +            return block()
А вы, кстати, сами-то не запинаетесь при чтении, когда так в одну строчку пишете?

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gamelogic/engines/items/Item.kt
> +        ) return null
Все сложные условия стоит выносить в отдельные предикаты. В вашем случае даже лучше на 2 предиката разбить (как раз по круглым скобочкам).

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gamelogic/engines/physics/PhysicsEngine.kt
> +        }
Обалдеть return крошечный.

2022-06-10 23:47 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/gamelogic/entities/scriptentities/Glitch.kt
> +        Glitch(targetCell, (units.first() as HpGameUnit).hp, clonePeriodMillis, teamId)
Вообще, подразумевалось, что клонов будет делать кто-то иной. При этом этот кто-то вообще не будет догадываться о том, что он клонирует, ибо всё будет спрятано за интерфейсом типа Clonable. Но ладно, паттерн простой, так что фиг с ним.

2022-06-11 14:53 UTC, DLochmelis33 commented on README.md
> +## Использование приложения
Теперь можно!

2022-06-11 15:04 UTC, DLochmelis33 commented on src/main/kotlin/ru/hse/sd/rgb/utils/CommonUtils.kt
> +val unreachable: Nothing get() = throw IllegalStateException("reached unreachable")
Наш `unreachable` &mdash; это по сути `assert(false)`: если дело дошло досюда, то все плохо от слова совсем (действительно unreachable). По сравнению с ассертом есть один бонус &mdash; не убирается во время релиз-компиляции. Ассерт, правда, бросает Error, а не Exception, но с другой стороны, IllegalState &mdash; непроверямое, так что если кто-нибудь решить его ловить, это на его совести. Впрочем, и мы можем при желании поменять это на Error или на свой Exception.

2022-06-11 15:30 UTC, DLochmelis33 commented
> у вас самореплицирующиеся мобы умеют в стены просачиваться

Так задумано, специально для глич**и** (моба Glitch, то бишь). Более того, чтобы это сделать нормально и не сломать никаких инвариантов, нам пришлось подумать и сделать не совсем тривиальное `PhysicalEntity.filterIncompatibleUnits()`. Зато теперь мы можем удобно сделать цвет, который будет периодически спаунить щиты вокруг героя, и не будет проблем с проверкой на стены-мобов-текущие щиты _(мы хотим сделать еще по-хорошему порядка 7-8 цветов и несколько мобов, stay tuned)_

> Со стратегиями и состояниями получилась каша

Обижаете :( Наша система Behaviour-ов &mdash; это наша гордость, там Автоматы Автоматовичи, просто мы еще не успели их нормально описать в документации. Но обязательно сделаем!

2022-06-11 15:49 UTC, DLochmelis33 commented on src/main/kotlin/ru/hse/sd/rgb/gameloaders/generators/MazeGenerator.kt
> +private data class Chamber(val lb: Cell, val ru: Cell) {
ru = right-upper!
___
Мы на все 100 за беззнаковые числа, но увы, разработчикам Котлина было лень писать хотя бы минимальную обертку над стандартной библиотекой Jav-ы _(если сделали nullable типы, то могли хотя бы разметить у существующих коллекций возвращаемые типы, ну камон)_, и поэтому они ни с чем, кроме себя, нормально не работают. Плюс, конкретно в этом случае запрет неявных кастов тоже совсем не помогает. А в каких-нибудь плюсах мы не задумываясь взяли бы `size_t` и ко.

2022-06-11 15:57 UTC, DLochmelis33 commented
К слову о MazeGenerator: когда он появился, мы им активно пользовались, и соответственно, пользовались паттерном Builder, который нужно было сделать. Но жизнь сложилась так, что мы решили сохранять описание уровней в YAML-файлах, и постепенно нам стало удобнее описывать всё в них. Поэтому если хочется, этим билдером всё еще можно воспользоваться из кода Main, но в последней версии он оказался не нужен. А сам паттерн мы применили еще раз в BehaviourBuilder (и там он поинтереснее и поосмысленнее).

2022-06-11 17:37 UTC, uncerso commented on src/main/kotlin/ru/hse/sd/rgb/utils/CommonUtils.kt
> +val unreachable: Nothing get() = throw IllegalStateException("reached unreachable")
Ух, автоматическое убирание ассертов -- гиблое дело. Для всяких тяжёлых проверок, обычно, делают специальный ключ на их включение. А мелкие проверки и так никакого влияния на перфоманс не несут. Ваш специально приспособленное исключение вполне ок выглядит, раз его заигнорить не получится случайно.

2022-06-11 18:01 UTC, uncerso commented
> Обижаете :( Наша система Behaviour-ов — это наша гордость

Ни в коем случае. Ваши система Behaviour-ов афигенные. Но хотелось, чтобы "состояние" и "стратегия" явно были отдельными сущностями в классическом варианте. А вы как раз взяли их в основу и сделали сложнее и круче, чем предполагалось.

2022-06-11 18:11 UTC, uncerso commented
> Так задумано, специально для гличи

А как его убить-то в итоге. Ничего же сквозь стены не проходит. И в итоге если оно решило засесть в стене, то press F.

Но как бы ладно, не баг, а фича, так сказать. :)

2022-06-11 19:43 UTC, DLochmelis33 commented
> А как его убить-то в итоге

А у нас обсчитываются столкновения для стен и всего, что на них сидит, так что надо пострелять или побиться головой в стенку 👍 Правда, если оно засядет в углу карты, то действительно будет не достать _(пока мы не добавили подходящий цвет, который дамажит всех в радиусе)_. Но к этому моменту гличи, вероятно, уже заполнили полуровня, и главной проблемой будут совсем не угловые

2022-06-24 17:18 UTC, GlebSolovev commented on README.md
> +./gradlew run
Действительно, иногда при первых запусках вместо игры просто черный экран, причем даже не на всех компьютерах и не всегда воспроизводится. Есть подозрение, что это что-то связанное со Swing-ой 😢

2022-06-24 17:21 UTC, GlebSolovev commented on README.md
> +./gradlew test
В конце вся статистика красиво выводится! Просто если какой-то тест падает, то остальные дальше не запускаются, по ним статистики нет &mdash; вероятно, такое поведение можно было бы улучшить.

Скрины из CI:
![image](https://user-images.githubusercontent.com/45554932/175611108-6d86d8b7-b251-4202-a4b8-40a7963c47c6.png)
![image](https://user-images.githubusercontent.com/45554932/175611153-998b90f8-8c19-4e69-9172-ddc54cc6e388.png)

2022-06-24 17:42 UTC, GlebSolovev commented on src/main/kotlin/ru/hse/sd/rgb/gamelogic/engines/behaviour/Lifecycle.kt
> +                        }
Все так! Просто иногда приходится нарушать такой подход, как ни странно, для лучшей читаемости: порой легче воспринимать некоторую логику именно в явном формате "если-иначе".

2022-06-24 17:46 UTC, GlebSolovev commented on src/main/kotlin/ru/hse/sd/rgb/gamelogic/engines/experience/ExperienceEngine.kt
> +            return block()
Наоборот, получаем некоторое извращенное удовольствие...

2022-06-24 19:59 UTC, GlebSolovev commented
Учли замечания по диздоку (добавили пропущенные элементы, поправили структуру, добавили диаграмму последовательностей) и немного улучшили код!

2022-06-25 08:15 UTC, yurii-litvinov approved these changes
Да, как-то так. У вас, как я понимаю, было основное замечание про диаграмму последовательностей, она появилась, выглядит ок, так что зачтена.

2022-06-25 08:15 UTC, yurii-litvinov commented on ARCHITECTURE.md
> +простых модов и/или скриптов.
По-хорошему надо обрисовать конкретного, хоть и выдуманного, персонажа, чтобы было понятно, для кого пишем. Чтобы не получился бот для Telegram для бабушек, напоминающий про то, когда забрать пенсию — всё хорошо, только бабушки Telegram не пользуются :)

2022-07-22 14:58 UTC, merged